### ISSUE TITLE
UnBan is can't working on CN server anymore

### ISSUE THREAD

**Issue by cerantes** [NightmareXIV/UnbanPluginsCN#1]
In light of the fact that an unknown UnBan clearing bannedplugin.json might cause you to load weird plugins and blow up the game, a refactoring of the logic has been done: the following

Good news: Moved Splatoon and other plugins out of bannedplugin.json
Bad news: cheatplugin.json has been added to unify the ban on related plugins
Bad news: bannedplugin.json will not load if it is empty, so the previous UnBan will no longer work
Good news: replacing bannedplugin.json in the UnBan code with cheatplugin.json will probably work
![QQ截图20230523094435](https://github.com/PunishXIV/Splatoon/assets/94860263/00badecc-8a6e-4fb9-b2c9-d34d354055ed)

-------------
The above message is from someone else, we have tested it and modifying cheatplugin.json is working

**Comment by LeNNo-tktk** [comment]
Can someone update an exe file?

**Comment by Limiana** [comment]
Should be updated now
