### ISSUE TITLE
The CN has changed the way to ban plugins

### ISSUE THREAD

**Issue by phoenix-yyj** [NightmareXIV/UnbanPluginsCN#12]
国服今天的更新后使用`cheatplugin.json`进行插件禁用，并且怀疑如果使用`XIVLauncherCN`并不会触发`Dalamud.updater`,所以代码无法生效

After the update of the Chinese server today, `cheatplugin.json` was used to disable the plugin, and it is suspected that if `XIVLauncherCN` is used, `Dalamud.updater` will not be triggered.

**Comment by WATjstHapen** [comment]
反馈：20241204，国服dalamud更新之后许多插件失效。目前的状况是unban.exe有效，service失效。您的#13内容 Program.cs 我不确定如何正确使用...抱歉

**Comment by Limiana** [comment]
Service is currently not working because it runs as a system rather than local user, just run the program as user

**Comment by phoenix-yyj** [comment]
> Service is currently not working because it runs as a system rather than local user, just run the program as user

It seems that the code in the repo is inconsistent with which the release build from.if that's true, please close my pr #13

**Comment by phoenix-yyj** [comment]
> 反馈：20241204，国服dalamud更新之后许多插件失效。目前的状况是unban.exe有效，service失效。您的#13内容 Program.cs 我不确定如何正确使用...抱歉

应该没事了,我以为服务不能使用是因为cheatplugin.json,所以修改了代码,但是似乎是仓库里的代码没有更新,release是更新了的.直接用用户启用exe就行

**Comment by WATjstHapen** [comment]
> > 反馈：20241204，国服dalamud更新之后许多插件失效。目前的状况是unban.exe有效，service失效。您的#13内容 Program.cs 我不确定如何正确使用...抱歉
> 
> 应该没事了,我以为服务不能使用是因为cheatplugin.json,所以修改了代码,但是似乎是仓库里的代码没有更新,release是更新了的.直接用用户启用exe就行

请问，那现在的情况依然是exe可用，service失效吗？这部分功能暂时没有更新是吗

**Comment by phoenix-yyj** [comment]
> > > 反馈：20241204，国服dalamud更新之后许多插件失效。目前的状况是unban.exe有效，service失效。您的#13内容 Program.cs 我不确定如何正确使用...抱歉
> > 
> > 
> > 应该没事了,我以为服务不能使用是因为cheatplugin.json,所以修改了代码,但是似乎是仓库里的代码没有更新,release是更新了的.直接用用户启用exe就行
> 
> 请问，那现在的情况依然是exe可用，service失效吗？这部分功能暂时没有更新是吗

实际上我提的 #13 打包出来的是可以使用service的,根本原因是因为注册服务会以管理员模式运行,导致获取到的`Appdata`不正确,我提的pr固定了目标目录,所以可以使用.

目前来说由于仓库代码似乎没有更新,我目前也没法解决service的部分.

如果不修改本体的话,使用`任务计划程序`手动创建一个任务,触发器为`登陆时`也是可以解决的.

**Comment by phoenix-yyj** [comment]
fix in #13

**Comment by phoenix-yyj** [comment]
fix in #13
