### ISSUE TITLE
FFXIVQuickLauncher failed to start Dalamud when UnbanPluginsCN is writing file

### ISSUE THREAD

**Issue by yuwenhuisama** [NightmareXIV/UnbanPluginsCN#4]
From the code of [FFXIVQuickLauncherCN](https://github.com/ottercorp/FFXIVQuickLauncher), I found that the client will first fetch `cheatplugin.json` and `bannedplugin.json` from server and try to write to disk. But when `UnbanPluginsCN` detected the modification of these 2 files, it would also write disk, so `FFXIVQuickLauncherCN` would fail to open the file to write things then it would reject to start `Dalamud`.

I have a workaround about this issue [LibrePatch-FFXIVQuickLauncherCN](https://github.com/yuwenhuisama/LibrePatch-FFXIVQuickLauncherCN/), but I think we could do more on this issue.

Could `UnbanPluginsCN` merge my workaround as the extension for `FFXIVQuickLauncherCN`?

**Comment by Limiana** [comment]
Hello!
Thank you for developing it. Right now I'm busy but I will take a look once I have a bit more free schedule.

However, I'd say that all this UnbanPlugins stuff can be considered no more than a temporary stuff.
I strongly suggest to the CN community that users of CN version of Dalamud and wants to use plugins freely cooperate and create a maintained and closely watched fork of CN Dalamud and FFXIVQuickLauncher with all this bans, telemetry and whatever else removed. 
Considering that simple Splatoon "banning" was now extended to other plugins as well and considering the fact that CN Dalamud fork started to gather information about users who circumvent their "ban", I would not be surprised if this will eventually end up like [this](https://boundingintocomics.com/2023/02/14/final-fantasy-xiv-modder-purposely-injects-malware-into-gshade-prompting-user-backlash/) or in a similar fashion.

**Comment by yuwenhuisama** [comment]
Thanks for your suggestion, I agree with your concern. I would like to summarize some facts for current CN community:
1. `Dalamud CN` and `FFXIVLauncher CN` currently maintains a major repo and have a list to ban plugins assigned by the maintainers, and also call other plugins outside the major repo as `third-party plugins`.
2. Currently `Dalamud CN` is not an open-source project (at lease I have not found the repo of `Dalamud CN` for now, so this is the most worrying point for CN users. (For my workaround `v2` strategy, I have to do some reverse-engineer on the `Dalamud CN`).
3. `FFXIVLauncher CN` is open-source and we could easily fork a branch to maintain a safe and free version. However, for `Dalamud CN` we have to fork from original `Dalamud` repo and do some adaption work and it will cost some time, so the temporary work-around such as `UnbanPluginsCN` is needed for now.

**Comment by Limiana** [comment]
https://github.com/ottercorp/Dalamud is this not CN Dalamud? Or do you mean injector?

**Comment by yuwenhuisama** [comment]
I'm not sure if this is Dalamud CN fork, but I will have a ckeck about this repo.

**Comment by Limiana** [comment]
Hopefully everything works fine nowadays
