### ISSUE TITLE
用了install service但是显示系统找不到指定的文件怎么办

### ISSUE THREAD

**Issue by S1mple-1ife** [NightmareXIV/UnbanPluginsCN#5]

**Comment by LeNNo-tktk** [comment]
same.
[SC] DeleteService 成功
[SC] CreateService 成功
[SC] ChangeServiceConfig2 成功
[SC] StartService 失败 2:

系统找不到指定的文件。

**Comment by Limiana** [comment]
Please make sure that contents of the folder where you have unpacked files has exactly 6 files with these names:
![image](https://github.com/NightmareXIV/UnbanPluginsCN/assets/5073202/5ca89a24-3ca3-4047-bf48-007c9ce68546)
Sometimes antivirus can eat executable in which case you'll need to add an exception.
Additionally, once the service has been installed, please do not move these files to another folder, as it will cause service to stop  functioning.

**Comment by ppzya** [comment]
现在用不了了嘛

**Comment by S1mple-1ife** [comment]
where can I find the two "Newtonsoft" files since it's not in the repository, thanks for your help

**Comment by S1mple-1ife** [comment]
never mind I found it on the new relaese
