### ISSUE TITLE
COULD NOT USED IN THE LATEST CN VERSION 10.0.0.16

### ISSUE THREAD

**Issue by zzlg-git** [NightmareXIV/UnbanPluginsCN#9]
Maybe the location of ban list is changed.
It's here now.
![image](https://github.com/user-attachments/assets/29791647-54c3-4006-9915-474fd3cba626)

**Comment by Limiana** [comment]
Hello, please try this version: https://github.com/NightmareXIV/UnbanPluginsCN/releases/tag/2.0.0.1

**Comment by zzlg-git** [comment]
> Hello, please try this version: https://github.com/NightmareXIV/UnbanPluginsCN/releases/tag/2.0.0.1

It works,thank you⌓‿⌓
